### ISSUE TITLE
Issue with binding on a specific IP

### ISSUE THREAD

**Issue by samary** [quattor/cdp-listend#15]
cdp-listend binds only on the IP given by the hostname lookup.
This make it not working on hosts having multiple IPs and being notified by another interface than the one given by the hostname IP lookup.

**Comment by ned21** [comment]
After discussion @samary confirmed that this is useful because their machines have external and internal network interfaces. The primary hostname is on the public interface but they want the Quattor notifications to come in on the private interface.

It would be useful of cdp-listend had a configuration option to allow it to listen on a different interface/name to the primary hostname, but as discussed this is not sufficient to make Quattor work with this setup because the system generating the notifications also has to know about the internal name. It may be easier to fix the other templates that assume the primary hostname is the "external" name rather than trying to allow the configuration name to be a secondary name.

**Comment by stdweird** [comment]
there are several ways around that issue from maual notifying the hosts (we use `echo "ccm.`date +%s`" > /dev/udp/$host/7777` :wink: ), to adding network routes on the dpeloy server for these non-standard hosts.
the fix itself is pretty straightforward, but the code is really ugly. i'll try to cleanup as little as possible for now

**Comment by stdweird** [comment]
@samary i assigned https://github.com/quattor/configuration-modules-core/issues/944 to you to add support for the new config option

**Comment by samary** [comment]
@stdweird : I tried and is seems to work. 
Although I couldn't use the notify ant task (seems to use the hostname in the profile to notify, not sure how notify finds it). 
I tested the notification using `nc -u $hostname_private 7777` passing `ccm TIMESTAMP` as argument.
We should maybe add a new attribute in the profile tree to specify the hostname to use for the notify ant task (could also be used to configure cdp-listend as well). I will try to find a way in #944.
